[package]
name = "crates_io"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2021"
default-run = "server"

[workspace]
members = ["crates_io_smoke_test"]

[profile.release]
opt-level = 2

[lib]
name = "crates_io"
doctest = true

[[test]]
name = "all"
path = "src/tests/all.rs"

[features]
default = ["slow-tests"]

# The `slow-tests` enables tests that take a long time to finish. It is enabled
# by default but the test suite can be run via `cargo test --no-default-features`
# to disable these tests.
slow-tests = []

[dependencies]
anyhow = "=1.0.75"
async-trait = "=0.1.73"
aws-sigv4 = "=0.56.1"
axum = { version = "=0.6.20", features = ["headers", "macros", "matched-path"] }
axum-extra = { version = "=0.8.0", features = ["cookie-signed"] }
base64 = "=0.21.4"
bigdecimal = "=0.4.1"
cargo-manifest = "=0.12.0"
crates_io_index = { path = "crates_io_index" }
crates_io_markdown = { path = "crates_io_markdown" }
crates_io_tarball = { path = "crates_io_tarball" }
chrono = { version = "=0.4.31", default-features = false, features = ["serde"] }
clap = { version = "=4.4.6", features = ["derive", "env", "unicode", "wrap_help"] }
cookie = { version = "=0.17.0", features = ["secure"] }
crossbeam-channel = "=0.5.8"
dashmap = { version = "=5.5.3", features = ["raw-api"] }
derive_deref = "=1.1.1"
dialoguer = "=0.11.0"
diesel = { version = "=2.1.3", features = ["postgres", "serde_json", "chrono", "r2d2", "numeric"] }
diesel_full_text_search = "=2.1.0"
diesel_migrations = { version = "=2.1.0", features = ["postgres"] }
dotenvy = "=0.15.7"
flate2 = "=1.0.27"
futures-channel = { version = "=0.3.28", default-features = false }
futures-util = "=0.3.28"
hex = "=0.4.3"
http = "=0.2.9"
http-body = "=0.4.5"
hyper = { version = "=0.14.27", features = ["backports", "client", "deprecated", "http1"] }
indexmap = { version = "=2.0.2", features = ["serde"] }
indicatif = "=0.17.7"
ipnetwork = "=0.20.0"
tikv-jemallocator = { version = "=0.5.4", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
lettre = { version = "=0.10.4", default-features = false, features = ["file-transport", "smtp-transport", "native-tls", "hostname", "builder"] }
minijinja = "=1.0.8"
moka = { version = "=0.11.3", features = ["future"]  }
oauth2 = { version = "=4.4.2", default-features = false, features = ["reqwest"] }
object_store = { version = "=0.7.1", features = ["aws"] }
once_cell = "=1.18.0"
parking_lot = "=0.12.1"
paste = "=1.0.14"
prometheus = { version = "=0.13.3", default-features = false }
rand = "=0.8.5"
reqwest = { version = "=0.11.22", features = ["blocking", "gzip", "json"] }
retry = "=2.0.0"
ring = "=0.17.2"
scheduled-thread-pool = "=0.2.7"
secrecy = "=0.8.0"
semver = { version = "=1.0.19", features = ["serde"] }
sentry = { version = "=0.31.7", features = ["tracing", "tower", "tower-axum-matched-path", "tower-http"] }
serde = { version = "=1.0.188", features = ["derive"] }
serde_json = "=1.0.107"
sha2 = "=0.10.8"
spdx = "=0.10.2"
tar = "=0.4.40"
tempfile = "=3.8.0"
thiserror = "=1.0.49"
threadpool = "=1.8.1"
tokio = { version = "=1.32.0", features = ["net", "signal", "io-std", "io-util", "rt-multi-thread", "macros"]}
toml = "=0.8.2"
tower = "=0.4.13"
tower-http = { version = "=0.4.4", features = ["fs", "catch-panic"] }
tracing = "=0.1.37"
tracing-subscriber = { version = "=0.3.17", features = ["env-filter"] }
url = "=2.4.1"

[dev-dependencies]
bytes = "=1.5.0"
crates_io_index = { path = "crates_io_index", features = ["testing"] }
crates_io_tarball = { path = "crates_io_tarball", features = ["builder"] }
claims = "=0.7.1"
hyper-tls = "=0.5.0"
insta = { version = "=1.33.0", features = ["json", "redactions"] }
tokio = "=1.32.0"
tower-service = "=0.3.2"

[build-dependencies]
diesel = { version = "=2.1.3", features = ["postgres"] }
diesel_migrations = { version = "=2.1.0", features = ["postgres"] }
dotenvy = "=0.15.7"
